/*
 * Problem #2
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
using System;
					
public class Problem2
{
	public static void Main()
	{
		int sum = 0;
		for( int f = 1, x = fib(f); x < 4000000; f++, x = fib(f), sum = ((x % 2 == 0) ? (sum + x) : sum) );
		Console.WriteLine(sum);
	}
	
	public static int fib( int cur )
	{
		return (cur == 0 || cur == 1 )
				? cur
				: fib( cur - 2) + fib(cur - 1);
	}
}
