/*
 * Problem #2
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
using System;
					
public class Problem2
{
	public static void Main()
	{
		int	runningTotal = 0, 
			T = 0,
			sequenceStart = 0,
			sequenceStep  = 1;
		
		while ( true )
		{
			T = sequenceStart;
			sequenceStart += sequenceStep;
			sequenceStep = T;
			
			runningTotal += (sequenceStart % 2 == 0) ? sequenceStart : 0;
			
			if (sequenceStart >= 4000000) 
			{
				break;
			}
		}
		
		Console.WriteLine("Running total: {0}", runningTotal);
	}
}
